### ISSUE TITLE
Cannot import Callabble from collection

### ISSUE THREAD

**Issue by uniwix** [squillero/microgp4#5]
Install fail using PyCharm, virtualenv and python 3.10.

```
Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\---\AppData\Local\Temp\pip-install-z8096sug\microgp_c429e2ce92064faf8b7ec9804d23db38\setup.py", line 48, in <module>
      from microgp import __version__ as ugp_version
    File "C:\Users\---\AppData\Local\Temp\pip-install-z8096sug\microgp_c429e2ce92064faf8b7ec9804d23db38\microgp\__init__.py", line 94, in <module>
      from .darwin import Darwin
    File "C:\Users\---\AppData\Local\Temp\pip-install-z8096sug\microgp_c429e2ce92064faf8b7ec9804d23db38\microgp\darwin.py", line 33, in <module>
      from .operators import Operators
    File "C:\Users\---\AppData\Local\Temp\pip-install-z8096sug\microgp_c429e2ce92064faf8b7ec9804d23db38\microgp\operators.py", line 27, in <module>
      from .genoperator import GenOperator
    File "C:\Users\---\AppData\Local\Temp\pip-install-z8096sug\microgp_c429e2ce92064faf8b7ec9804d23db38\microgp\genoperator.py", line 28, in <module>
      from collections import Callable
  ImportError: cannot import name 'Callable' from 'collections' (C:\Users\---\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)
```

FIX: update `from collections import Callable` to `from collection.abc import Callable` in `genoperator.py`.

**Comment by rama225** [comment]
Extension error:
Could not import extension sphinxcontrib.napoleon (exception: cannot import name 'Callable' from 'collections' (C:\Users\tarak\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py))

I am also getting the same error bro while build like make html. 

Have you solved your issue bro?

**Comment by SamsonBui00** [comment]
> 

Thx , u are a life saver
